"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, CalendarDays } from "lucide-react";
import { getPlayer, getPlayerHistory } from "@/lib/api/players";
import type { PlayerDetail, PlayerHistoryResponse } from "@/lib/api/types";
import { euro, dateLabel } from "@/lib/format";
import { ErrorState, Skeleton } from "@/components/shared/States";
import { TrendBadge } from "@/components/shared/TrendBadge";
import { MarketChart } from "@/components/charts/MarketChart";
export default function PlayerDetailPage({ params }: { params: { id: string } }) { const [player, setPlayer] = useState<PlayerDetail>(); const [history, setHistory] = useState<PlayerHistoryResponse>(); const [error, setError] = useState(false); useEffect(() => { Promise.all([getPlayer(params.id), getPlayerHistory(params.id, { limit: 90 })]).then(([p, h]) => { setPlayer(p); setHistory(h); }).catch(() => setError(true)); }, [params.id]); if (error) return <ErrorState text="Dieser Spieler wurde nicht gefunden oder die API ist nicht erreichbar."/>; if (!player || !history) return <><Skeleton className="h-10 w-64"/><Skeleton className="mt-8 h-96 w-full"/></>; const latest = history.items[0]; return <><Link href="/spieler" className="mb-8 inline-flex items-center gap-2 text-sm text-secondary hover:text-accent"><ArrowLeft size={16}/> Zur Spielerliste</Link><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow">Spielerprofil · {player.position}</p><h1 className="mt-2 text-4xl font-bold">{player.name}</h1><p className="mt-2 text-secondary">{player.team_name ?? "Ohne Team"}</p></div><div className="text-left md:text-right"><p className="eyebrow">Aktueller Marktwert</p><p className="mt-2 font-mono text-3xl font-bold">{euro(player.current_value_eur)}</p>{latest && <TrendBadge value={latest.delta_previous_day_eur} rate={latest.percent_delta_previous_day}/>}</div></div><div className="mt-8 grid gap-6 lg:grid-cols-[1.5fr_1fr]"><section className="panel p-6"><div className="flex items-center justify-between"><div><p className="eyebrow">Historie</p><h2 className="mt-2 text-xl font-bold">Marktwertentwicklung</h2></div><span className="inline-flex items-center gap-2 text-xs text-secondary"><CalendarDays size={15}/> 90 Tage</span></div>{history.items.length ? <MarketChart data={history.items}/> : <p className="py-24 text-center text-secondary">Noch keine Historie vorhanden.</p>}</section><section className="space-y-6"><div className="panel p-6"><p className="eyebrow">Seit Erstsichtung</p><p className="mt-3 font-mono text-2xl font-bold">{euro(latest?.delta_first_eur)}</p><p className="mt-2 text-sm text-secondary">Veränderung seit {dateLabel(latest?.first_snapshot_date)}</p><div className="mt-6 border-t border-line pt-5"><TrendBadge value={latest?.delta_first_eur ?? null} rate={latest?.percent_delta_first}/></div></div><div className="panel p-6"><p className="eyebrow">Datenquelle</p><p className="mt-3 text-sm text-secondary">{player.source}</p><p className="mt-2 text-xs text-muted">Letzte Sichtung: {dateLabel(player.last_seen_at)}</p></div></section></div></>; }