import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { euro } from "@/lib/format";
import type { PlayerSummary, TeamSummary, TransferMarketItem } from "@/lib/api/types";
const positionLabel = { TW: "Torwart", ABW: "Abwehr", MITT: "Mittelfeld", ST: "Sturm" };
export function PositionBadge({ position }: { position: keyof typeof positionLabel }) { return <span className="rounded-md border border-violet/30 bg-violet/10 px-2 py-1 text-xs font-semibold text-violet">{position}</span>; }
export function PlayerTable({ items }: { items: PlayerSummary[] }) { return <TableFrame head={<tr><th>Name</th><th>Position</th><th>Team</th><th className="text-right">Marktwert</th><th/></tr>}><tbody>{items.map((player) => <tr key={player.id}><td className="font-semibold">{player.name}</td><td><PositionBadge position={player.position}/></td><td className="text-secondary">{player.team_name ?? "-"}</td><td className="text-right font-mono">{euro(player.current_value_eur)}</td><td className="text-right"><Link className="inline-flex text-accent" aria-label={`${player.name} Details`} href={`/spieler/${player.id}`}><ArrowUpRight size={17}/></Link></td></tr>)}</tbody></TableFrame>; }
export function TeamTable({ items }: { items: TeamSummary[] }) { return <TableFrame head={<tr><th>Team</th><th>Liga</th><th>Saison</th><th className="text-right">Kader</th><th/></tr>}><tbody>{items.map((team) => <tr key={team.id}><td className="font-semibold">{team.name}</td><td className="text-secondary">{team.league ?? "-"}</td><td className="text-secondary">{team.season ?? "-"}</td><td className="text-right">{team.player_count}</td><td className="text-right"><Link className="inline-flex text-accent" aria-label={`${team.name} Details`} href={`/teams/${team.id}`}><ArrowUpRight size={17}/></Link></td></tr>)}</tbody></TableFrame>; }
export function TransferTable({ items, showOwner }: { items: TransferMarketItem[]; showOwner: boolean }) { return <TableFrame head={<tr><th>Spieler</th><th>Team</th><th>Position</th><th>Preis</th>{showOwner && <th>Besitzer</th>}<th>Status</th></tr>}><tbody>{items.map((item) => <tr key={`${item.player_id}-${item.snapshot_date}`}><td><Link className="font-semibold hover:text-accent" href={`/spieler/${item.player_id}`}>{item.player_name}</Link></td><td className="text-secondary">{item.team_name ?? "-"}</td><td><PositionBadge position={item.position}/></td><td className="font-mono">{euro(item.price_eur)}</td>{showOwner && <td className="text-secondary">{item.owner_name ?? "-"}</td>}<td><span className={item.listed ? "text-success" : "text-muted"}>{item.listed ? "angeboten" : "nicht gelistet"}</span></td></tr>)}</tbody></TableFrame>; }
function TableFrame({ head, children }: { head: React.ReactNode; children: React.ReactNode }) { return <div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="border-b border-line text-xs uppercase tracking-wide text-muted">{head}</thead>{children}</table></div>; }